/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Zarr attributes containing convention metadata and proj: prefixed properties
 */
export type ProjAttributes = {
  /**
   * Array of convention metadata objects
   */
  zarr_conventions: unknown[];
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};

/**
 * Schema for geospatial coordinate reference system information in Zarr. Properties use the 'proj:' namespace prefix.
 */
export interface GeospatialProjectionConventionProj {
  /**
   * Zarr format version
   */
  zarr_format: number;
  /**
   * Type of Zarr node
   */
  node_type: "array" | "group";
  attributes: ProjAttributes;
  [k: string]: unknown;
}
