/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for multiscale pyramid information in Zarr
 */
export interface MultiscalesConvention {
  /**
   * Zarr format version
   */
  zarr_format: number;
  /**
   * Type of Zarr node (multiscales only applies to groups)
   */
  node_type: "group";
  /**
   * Zarr attributes containing convention metadata and properties
   */
  attributes: {
    /**
     * Array of convention metadata objects
     */
    zarr_conventions: unknown[];
    multiscales: MultiscalesProperties;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Multiscales convention properties defining the hierarchical layout and transformations
 */
export interface MultiscalesProperties {
  /**
   * Array of objects representing the pyramid layout and transformation relationships
   *
   * @minItems 1
   */
  layout: [LayoutObject, ...LayoutObject[]];
  /**
   * Default resampling method used for downsampling
   */
  resampling_method?: string;
  [k: string]: unknown;
}
/**
 * Layout object representing a single resolution level
 */
export interface LayoutObject {
  /**
   * Path to the Zarr group or array for this resolution level. Can be a simple name (e.g., '0') for a child group, or a path with '/' separator for nested groups or arrays (e.g., '0/data' for an array within a group)
   */
  asset: string;
  /**
   * Path to the source Zarr group or array used to generate this level. Uses the same path syntax as 'asset' with '/' separator for nested resources
   */
  derived_from?: string;
  /**
   * Transformation parameters describing the coordinate transformation for this level. Contains relative transformation parameters (scale, translation). Absolute positioning parameters should be placed at the layout entry level, outside this object.
   */
  transform?: {
    /**
     * Array of scale factors per axis describing the coordinate transformation from the source level (derived_from) to this level
     */
    scale?: number[];
    /**
     * Array of translation offsets per axis in the coordinate space
     */
    translation?: number[];
    [k: string]: unknown;
  };
  /**
   * Default resampling method used for resampling data
   */
  resampling_method?: string;
  [k: string]: unknown;
}
