/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for spatial coordinate information in Zarr. Properties use the 'spatial:' namespace prefix. This convention defines the relationship between array indices and spatial coordinates.
 */
export interface SpatialCoordinateConventionSpatial {
  /**
   * Zarr format version
   */
  zarr_format: number;
  /**
   * Type of Zarr node
   */
  node_type: "array" | "group";
  attributes: SpatialAttributes;
  [k: string]: unknown;
}
/**
 * Zarr attributes containing convention metadata and spatial: prefixed properties
 */
export interface SpatialAttributes {
  /**
   * Array of convention metadata objects
   */
  zarr_conventions: unknown[];
  [k: string]: unknown;
}
