# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "imageio>=2.37.3",
#     "numpy>=2.4.4",
#     "rio-tiler>=9.0.6",
# ]
# ///
"""
Generate the colormap sprite asset and a TypeScript name→index mapping.

Outputs (into the package's src/gpu-modules/ directory by default):
- colormaps.png      N x 256 x 4 RGBA8 image; one row per colormap.
- colormap-names.ts  Generated TypeScript: COLORMAP_INDEX constant + type.

Run with:
    uv run packages/deck.gl-raster/scripts/generate_colormaps.py
"""

from pathlib import Path

from imageio.v3 import imwrite
import numpy as np
from rio_tiler.colormap import cmap as cmap_registry
from rio_tiler.colormap import make_lut


OUT_DIR = Path(__file__).resolve().parent.parent / "src" / "gpu-modules"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    names = sorted([x for x in cmap_registry.list() if not x.endswith("_r")])

    # Each row is one 256-entry LUT of shape (256, 4) uint8.
    rows = [
        # (rio-tiler has bad type annotations)
        make_lut(cmap_registry.get(name))  # type: ignore[arg-type]
        for name in names
    ]

    sprite = np.stack(rows, axis=0)  # (N, 256, 4)

    # Sanity check: all LUTs are 256 entries.
    assert sprite.shape[1] == 256, (
        f"expected 256-entry LUTs, got width {sprite.shape[1]}"
    )

    imwrite(OUT_DIR / "colormaps.png", sprite)

    ts_lines = [
        "// Generated by scripts/generate_colormaps.py. Do not edit by hand.",
        "",
        "export const COLORMAP_INDEX = {",
    ]
    for i, name in enumerate(names):
        ts_lines.append(f'  "{name}": {i},')
    ts_lines.append("} as const;")
    ts_lines.append("")
    ts_lines.append("export type ColormapName = keyof typeof COLORMAP_INDEX;")
    ts_lines.append("")

    (OUT_DIR / "colormap-names.ts").write_text("\n".join(ts_lines))

    print(f"Wrote {len(names)} colormaps to {OUT_DIR}")


if __name__ == "__main__":
    main()
