import type { ShaderModule } from "@luma.gl/shadertools";
import { lngLatToWorld } from "@math.gl/web-mercator";

export type CutlineBboxProps = {
  /**
   * WGS84 axis-aligned bbox as `[west, south, east, north]` in degrees.
   *
   * Must satisfy `east > west` (antimeridian crossing is not supported) and
   * `north > south`. Latitudes must lie within the Web Mercator limits
   * (±85.051129°).
   */
  bbox: [number, number, number, number];
};

const MODULE_NAME = "cutlineBbox";

const uniformBlock = `\
uniform ${MODULE_NAME}Uniforms {
  vec4 bbox;
} ${MODULE_NAME};
`;

/**
 * A shader module that discards fragments whose position falls outside a
 * WGS84 axis-aligned bbox.
 *
 * Intended for rendering rasters with a "map collar" (e.g. USGS historical
 * topographic maps) where the valid data area is described as a lat/lng bbox
 * but the raw pixels include surrounding metadata.
 *
 * Only supports rendering in a `WebMercatorViewport`. The caller is
 * responsible for enforcing this in application code; the module itself does
 * not have viewport access.
 */
export const CutlineBbox = {
  name: MODULE_NAME,
  fs: uniformBlock,
  inject: {
    // We inject at fs:#main-start (the beginning of the FS main function body)
    // rather than fs:DECKGL_FILTER_COLOR. DECKGL_FILTER_COLOR is generated by
    // luma.gl as a separate hook *function*, which only has access to its
    // parameters (color, geometry) and to top-level uniforms — the
    // position_commonspace varying is declared in the main shader source that
    // is assembled after the hook function, so it is out of scope there.
    // Injecting at #main-start puts our test inside main() where the varying
    // is in scope and `discard` still works.
    //
    // Globe support: when rendering in a GlobeView, the mesh positions are in
    // 4326 lng/lat rather than 3857 meters, so `position_commonspace` is no
    // longer directly comparable to a 3857-meter bbox. A future globe code
    // path would need a different varying and a matching uniform layout.
    "fs:#main-start": /* glsl */ `
      {
        vec2 cutlineBboxPos = position_commonspace.xy;
        if (cutlineBboxPos.x < ${MODULE_NAME}.bbox.x ||
            cutlineBboxPos.x > ${MODULE_NAME}.bbox.z ||
            cutlineBboxPos.y < ${MODULE_NAME}.bbox.y ||
            cutlineBboxPos.y > ${MODULE_NAME}.bbox.w) {
          discard;
        }
      }
    `,
  },
  uniformTypes: {
    bbox: "vec4<f32>",
  },
  getUniforms: (props: Partial<CutlineBboxProps>) => {
    const bbox = props.bbox;
    if (!bbox) {
      return {};
    }
    const [west, south, east, north] = bbox;
    if (!(east > west)) {
      throw new Error(
        `CutlineBbox: bbox must have east > west (antimeridian crossing is not supported); got west=${west}, east=${east}`,
      );
    }
    if (!(north > south)) {
      throw new Error(
        `CutlineBbox: bbox must have north > south; got south=${south}, north=${north}`,
      );
    }
    const MERCATOR_LAT_LIMIT = 85.051129;
    if (
      south < -MERCATOR_LAT_LIMIT ||
      south > MERCATOR_LAT_LIMIT ||
      north < -MERCATOR_LAT_LIMIT ||
      north > MERCATOR_LAT_LIMIT
    ) {
      throw new Error(
        `CutlineBbox: bbox latitudes must be within Web Mercator limits (±${MERCATOR_LAT_LIMIT}°); got south=${south}, north=${north}`,
      );
    }
    const [swX, swY] = lngLatToWorld([west, south]);
    const [neX, neY] = lngLatToWorld([east, north]);
    return {
      bbox: [
        Math.min(swX, neX),
        Math.min(swY, neY),
        Math.max(swX, neX),
        Math.max(swY, neY),
      ],
    };
  },
} as const satisfies ShaderModule<CutlineBboxProps>;
